### ISSUE TITLE
good stuff but... don't put your oauth tokens on git

### ISSUE THREAD

**Issue by unsalted** [kvfrans/twitch-emotes#1]
Interesting stuff, helped me outline some of the problem set of something im currently developing, keep up the good work.

Just a heads up, you may not want to put your oauth username and token on git.

Store them in an env file (like a env.js) and use .gitignore to exclude them from your upload.

Otherwise someone might take over your account and emulate you with a bot trained on Sarah Palin.

**Comment by kvfrans** [comment]
Yeah I thought about keeping it more secure, but that Twitch account is only for this one project so I can read the Twitch IRC so there's not that much that could go wrong

**Comment by unsalted** [comment]
Fair enough, well written blog post, i'm trying to replicate some of what you wrote using the keras lib, it has most of the tokenization and data modeling stuff you wrote built in  - but I must admit i'm new to rnn's so it's a lot to digest.

**Comment by myh1000** [comment]
#2 I've just removed the oauth token from scrape.js, will probably note in the README.md that users will have to supply their own tokens if they want to scrape messages from Twitch.
